### ISSUE TITLE
Day 17 part 1 return erroneous results with some inputs

### ISSUE THREAD

**Issue by dreherch** [entwanne/advent-of-code-2021#1]
Hi,

With some inputs, for instance
`target area: x=29..73, y=-248..-194`
part 1 return invalid result (7503, while 30628 is expected).

The right result was obtained by expanding ampl in part 1 to match its computation in part 2. The results on sample data and your input remained unchanged, and the result for the `target area: x=29..73, y=-248..-194` was fixed (at the cost of extended computation time). However, no proper analysis was done to ensure this is a valid fix for the issue.

```
diff --git a/d17_p1.py b/d17_p1.py
index 0d41a69..c846cb4 100644
--- a/d17_p1.py
+++ b/d17_p1.py
@@ -30,7 +30,7 @@ def check_velocity(vel):
         vy -= 1
 
 
-ampl = max(abs(xmin), abs(xmax), abs(ymin), abs(ymax)) // 2
+ampl = max(abs(xmin), abs(xmax), abs(ymin), abs(ymax)) + 1
 
 checks = (check_velocity(vel) for vel in product(range(ampl), range(ampl)))
 topy = max(y for check, y in checks if check)
```

**Comment by entwanne** [comment]
Ok thanks, I tried this "optimization" after I solved the exercise as I wanted a curve where the top of the bell would be approximatively at the middle of the path. I'll revert this change.
